version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: CDEK_postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Petr
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: CDEK_WORK
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: